# -*- coding: utf-8 -*-
"""classifier_fastai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKpWFNpoz98mu3IgUSd4r7VMEUG57r-F
"""

from fastai.vision.all import *

path = untar_data(URLs.PETS)/ 'images'

def is_cat(x): return x[0].isupper()

dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224)
)

learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)

# Import the necessary module
import ipywidgets as widgets

# Now you can use the FileUpload widget
uploader = widgets.FileUpload()
uploader

img = PILImage.create(uploader.data[0])
is_cat,_,probs = learn.predict(img)
print(f"Is this a cat?: {is_cat}.")
print(f"Probability it's a cat: {probs[1].item():.6f}")

